/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SavedPlanRouteImport } from './routes/saved-plan'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as DetailsRouteImport } from './routes/details'
import { Route as Checkout_flowRouteImport } from './routes/checkout_flow'
import { Route as IndexRouteImport } from './routes/index'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedPlanRoute = SavedPlanRouteImport.update({
  id: '/saved-plan',
  path: '/saved-plan',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const DetailsRoute = DetailsRouteImport.update({
  id: '/details',
  path: '/details',
  getParentRoute: () => rootRouteImport,
} as any)
const Checkout_flowRoute = Checkout_flowRouteImport.update({
  id: '/checkout_flow',
  path: '/checkout_flow',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/checkout_flow': typeof Checkout_flowRoute
  '/details': typeof DetailsRoute
  '/explore': typeof ExploreRoute
  '/saved-plan': typeof SavedPlanRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checkout_flow': typeof Checkout_flowRoute
  '/details': typeof DetailsRoute
  '/explore': typeof ExploreRoute
  '/saved-plan': typeof SavedPlanRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/checkout_flow': typeof Checkout_flowRoute
  '/details': typeof DetailsRoute
  '/explore': typeof ExploreRoute
  '/saved-plan': typeof SavedPlanRoute
  '/settings': typeof SettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/checkout_flow'
    | '/details'
    | '/explore'
    | '/saved-plan'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/checkout_flow'
    | '/details'
    | '/explore'
    | '/saved-plan'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/checkout_flow'
    | '/details'
    | '/explore'
    | '/saved-plan'
    | '/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Checkout_flowRoute: typeof Checkout_flowRoute
  DetailsRoute: typeof DetailsRoute
  ExploreRoute: typeof ExploreRoute
  SavedPlanRoute: typeof SavedPlanRoute
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved-plan': {
      id: '/saved-plan'
      path: '/saved-plan'
      fullPath: '/saved-plan'
      preLoaderRoute: typeof SavedPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/details': {
      id: '/details'
      path: '/details'
      fullPath: '/details'
      preLoaderRoute: typeof DetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout_flow': {
      id: '/checkout_flow'
      path: '/checkout_flow'
      fullPath: '/checkout_flow'
      preLoaderRoute: typeof Checkout_flowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Checkout_flowRoute: Checkout_flowRoute,
  DetailsRoute: DetailsRoute,
  ExploreRoute: ExploreRoute,
  SavedPlanRoute: SavedPlanRoute,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
